### ISSUE TITLE
Tab Groupings Not Working?

### ISSUE THREAD

**Issue by ryanbuening** [jdhayford/acid-tabs-extension#12]
I am a first time user. I installed 6.5.2 and am on Chrome 91.0.4472.164. None of my groupings seem to be working. I am also not seeing anything in the extension options page except for the text "SETTINGS PAGE".

![image](https://user-images.githubusercontent.com/812974/126338730-c7323490-8d41-4da1-a534-2f7e9671500d.png)

**Comment by jdhayford** [comment]
> Good catch. It turns out the extension really does need "tabs" permissions after all 🙄 . Not sure why the chrome team told me it didn't. I'm pushing an update to add it back in now.

Relevant to the discussion here: https://github.com/jdhayford/acid-tabs-extension/issues/11

We are waiting for the update to be approved by the Chrome store.

**Comment by jdhayford** [comment]
This update should now be live in `6.5.3`. Please let me know if you have this version but are still experiencing problems.

**Comment by ryanbuening** [comment]
Fixed for me! Thanks.
