### ISSUE TITLE
Tab Groups get nested weirdly when using pinned tabs

### ISSUE THREAD

**Issue by 6112** [jdhayford/acid-tabs-extension#21]
Repro:

1. Pin a couple tabs
2. Create a handful of group patterns, e.g. one for example.com, one for example.org, and one for example.net
3. Open a few example.org/com/net tabs
4. Manipulate the tabs a bit to make them update their state (e.g., make them refresh, move them around)

I would expect each group (org/com/net) to remain separate,  but it actually nests the tab groups within eachother, in an inconsistent way. It's hard/impossible to undo this nesting, as the groups will get yanked back inside another group if you manipulate them

**Comment by MizardX** [comment]
This should be fixed with PR #16. There has not been any new release since then though.

**Comment by jdhayford** [comment]
Version 6.5.4, now published on the store, should @MizardX 's fix (thanks again)
