### ISSUE TITLE
Tabs not grouping; tab groups undefined

### ISSUE THREAD

**Issue by bsell93** [jdhayford/acid-tabs-extension#32]
It appears for some reason `chrome.tabGroups.query` is returning `undefined` and therefore is breaking `getTabGroup` by id. 

<img width="702" alt="image" src="https://user-images.githubusercontent.com/5335177/175057497-1be70097-43aa-4412-a09f-74bbaed900cb.png">
<img width="697" alt="image" src="https://user-images.githubusercontent.com/5335177/175057533-92a32d7e-e042-45bb-8689-ee5754b5c9e5.png">

The behavior looks something like this. None of my groups are grouping as expected and all are missing titles
![image](https://user-images.githubusercontent.com/5335177/175057680-3ec79b75-ec08-4b1a-99ae-2d822b4b4dd4.png)

Note: The source code screenshot is of main branch with some added console logs. I'm seeing the same behavior from the "deployed" version from the extension store

**Comment by OhYee** [comment]
have the same problem，and #33 works

**Comment by jdhayford** [comment]
@bsell93 Thanks! Looking at it now

**Comment by jdhayford** [comment]
This is now released in `6.5.5` thanks @bsell93 !
